[package]
name = "rustsqrl"
version = "0.1.0"
authors = ["Vegar Westerlund <vegarwe@gmail.com>"]
edition = "2018"

[dependencies]
extfmt = "0.1.1"
byte = "0.2"
scrypt = { version = "0.2", default-features = false }
